#version 430

layout(local_size_x = 256) in;

struct Particle {
    vec4 pos;
    vec4 velocity;
    vec4 color;
    float life;
    float maxLife;
    int padding1;
    int padding2;
};

layout(std430, binding = 0) buffer Particles {
    Particle particles[];
};

uniform float dt;         // delta time
uniform vec3 basePos;     // fire source
uniform float time;       // global time

// Simple pseudo-random generator
float rand(float seed) {
    return fract(sin(seed) * 43758.5453);
}

// Generate random direction
vec3 randomDir(float seed) {
    float x = rand(seed) * 2.0 - 1.0;
    float y = rand(seed + 1.0);
    float z = rand(seed + 2.0) * 2.0 - 1.0;
    return normalize(vec3(x, y, z));
}

void respawn(inout Particle p, uint id) {
    float seed = float(id) + time;

    vec3 dir = randomDir(seed);
    
    p.pos.xyz = basePos + dir * 0.1;
    //p.pos.xyz = dir * 0.1;
    
    // Fire rises upward
    p.velocity.xyz = vec3(
        dir.x * 0.5,
        1.0 + rand(seed),
        dir.z * 0.5
    );

    p.color = vec4(1.0, 1.0, 1.0, 1.0);

    p.maxLife = 1.0 + rand(seed) * 2.0;
    p.life = p.maxLife;
}

void main() {
    uint id = gl_GlobalInvocationID.x;
    Particle p = particles[id];

    if (p.life <= 0.000001) {
        respawn(p, id);
    } else {
        // Decrease life
        p.life -= dt;

        float t = p.life / p.maxLife;
        // Fire gradient
        vec3 color = mix(vec3(1.0, 0.1, 0.0), vec3(1.0, 1.0, 0.0), t);

        // white -> yellow -> red
        
        //vec3 color = vec3(1.0 - 0.5 * t, 
        //        exp(4 * (t - 1.0) ) , exp(10 * (t - 1.0)));

        p.color = vec4(color, 1.0);

        // Upward acceleration (buoyancy)
        p.velocity.y += 0.5 * dt;

        // Add turbulence
        float noise = rand(float(id) + time) - 0.5;
        p.velocity.x += noise * 0.5 * dt;
        p.velocity.z += noise * 0.5 * dt;

        // Update position
        p.pos.xyz += p.velocity.xyz * dt;
    }

    particles[id] = p;
}